### ISSUE TITLE
I do not find the ./data folder

### ISSUE THREAD

**Issue by alessandro-gentilini** [darrenstrash/quick-cliques#5]
Hello, in `README.md` you wrote about a `./data` folder but I do not find it.

**Comment by darrenstrash** [comment]
Thanks for letting me know! The folder was accidentally removed, but was in the original released. The data folder is now back. Please pull the changes from the repo.

**Comment by alessandro-gentilini** [comment]
> Thanks for letting me know! The folder was accidentally removed, but was in the original released. The data folder is now back. Please pull the changes from the repo.

Thank you very much for your help!
