### ISSUE TITLE
Getting 'St9bad_alloc' what(): std::bad_alloc on Windows

### ISSUE THREAD

**Issue by ezequielscott** [darrenstrash/quick-cliques#7]
I'm trying to calculate the cliques of a large graph on Windows but I get the following error:

`terminate called after throwing an instance of 'St9bad_alloc' what(): std::bad_alloc`

Running on Win x64, 16GB momory, Intel Core i7
quick-cliques compiled using Cygwin
Graph: nodes: 20000; edges: 199417563
Algorithms used: hybrid and degeneracy

I run the same command on Mac and it works well, but I really need to get this working on Win. Any suggestions?

**Comment by armintoepfer** [comment]
Sounds like you are running out of memory.

**Comment by ezequielscott** [comment]
Why does it work well on Mac then (if I have same memory 16 Gb)?

I also checked the task manager, and the system never uses all the memory when computing.

**Comment by darrenstrash** [comment]
This exception is thrown when you are out of memory. Windows typically uses a lot more memory than Mac OSX. Your graph is also very dense, in which case an adjacency matrix might be better and use less memory. Try using tomita and see if that works for you. Note that if you are hoping to do timing tests, my implementation of tomita is slower than the original.

**Comment by darrenstrash** [comment]
Note that your system doesn't have to be completely out of memory to get this error. Operating systems manage the memory and it can get very fragmented, in which case you could see this error if there is no fragment large enough. Also, the task manager is not an accurate gauge for how much memory a process is using in real-time. It polls the program and can miss the moment it uses the max memory. You would want to use a tool such as massif to look at the memory footprint.

**Comment by ezequielscott** [comment]
Thanks for the prompt answers!

When you suggest using an adjacency matrix, you mean to use a different format for my graph such as the one supported by the implementation? "The unweighted METIS format"

**Comment by darrenstrash** [comment]
It's the data structure used in the code. This wouldn't require any changes to the graph on your side. My code for the algorithm "tomita" uses an adjacency matrix. See if changing the algorithm to "tomita" works for you on Windows. This will also probably be a lot faster than the degeneracy or hybrid algorithms, since your graph is so dense.

**Comment by ezequielscott** [comment]
I tried "tomita" and I got the following error:

`ERROR!: unable to compute adjacencyMatrix, since the graph is too large: 20000 vertices.`

So far, "hybrid" and "degeneracy" works very well on Mac. 

I will investigate how to make a better use of memory on Win

**Comment by darrenstrash** [comment]
This is an artificial (but reasonable) size limit I set to prevent it from using too much memory. If you feel comfortable editing the code, change line 169 in src/main.cpp from:

`bool const bComputeAdjacencyMatrix(adjacencyList.size() < 20000);`

to

`bool const bComputeAdjacencyMatrix(adjacencyList.size() < 25000);`

and see if it works for you.

**Comment by ezequielscott** [comment]
Tomita didn't work in my case (even when I changed that line of code to support more nodes), but the tool did well with the algorithm "hybrid". 

Definitely, MacOS and Linux have better memory management than Windows, so I solved my issue by running the code on Windows using the **Windows Subsystem for Linux (WSL)**. It worked well!

**Comment by darrenstrash** [comment]
Glad to hear it! I will close the issue.
